### ISSUE TITLE
Node_modules uploded to github.

### ISSUE THREAD

**Issue by LeoFC97** [luisscoelho/api_usuarios#1]
Hey Luis, you dont need to upload the node_modules folder to github, in fact its a problem  when you do it. 

You just need to upload your pacakge.json file. With the package.json everyone can install the libraries with: **npm install**.

You can read more about this here: 
https://flaviocopes.com/should-commit-node-modules-git/
https://pt.stackoverflow.com/questions/517998/%C3%89-necess%C3%A1rio-versionar-a-pasta-node-modules-no-git

**Comment by luiscoelhodev** [comment]
Thanks for the tip, @LeoFC97! Just fixed it by sending the node_modules to .gitignore.
